services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-22.04
    container_name: sqlserver2022
    hostname: sqlserver2022
    environment:
      MSSQL_SA_PASSWORD: "SqlServer2022!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql-data:/var/opt/mssql/data